modLoader = "javafml"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "Mozilla Public License 2.0"

[[mods]]
modId = "ccspeakercodecs"
version = "${version}"
displayName = "CCSpeakerCodecs"
authors = "JackMacWindows"
description = '''
Adds a collection of alternate transit codecs for CC: Tweaked speakers to improve audio quality.
'''
#logoFile = ""

[[dependencies.ccspeakercodecs]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ccspeakercodecs]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.20.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.ccspeakercodecs]]
modId = "computercraft"
mandatory = true
versionRange = "[1.110.0,)"
ordering = "AFTER"
side = "BOTH"
